### ISSUE TITLE
Style not working right with vuetify

### ISSUE THREAD

**Issue by AldeonMoriak** [ckeditor/ckeditor5-vue2#12]
Hello, 
when using ckeditor5 with vuetify there are some problems with styling.
Like in lists.
I have reproduces the bug in [here](https://codesandbox.io/s/ckeditor-vuetify-veevalidate3-forked-cwqdo?file=/src/components/HelloWorld.vue).

**Comment by AldeonMoriak** [comment]
It is a problem with vuetify

**Comment by a54552239** [comment]
> It is a problem with vuetify

I have the same problem

**Comment by etiennewayne** [comment]
does anyone fix this problem?
