### ISSUE TITLE
this.$_instance is undefined error

### ISSUE THREAD

**Issue by andy3471** [ckeditor/ckeditor5-vue2#21]
I'm getting the error this.$_instance is undefined when using ckeditor5-vue2 3.0.0 with Vue 2.6.12.

![Screenshot from 2022-05-03 16-28-06](https://user-images.githubusercontent.com/7016492/166484920-9af1f2b5-d87c-4e99-83d2-6c53ad8cf4b1.png)

This was fixed in the ckeditor-vue3 in [PR209](https://github.com/ckeditor/ckeditor5-vue/pull/209), however the changes do not seem to be in ckeditor5-vue2, and the error still persists.

**Comment by FilipTokarski** [comment]
@psmyrek Could you take a look at this? 🙏

**Comment by psmyrek** [comment]
Thank you for reporting this issue. The mentioned PR https://github.com/ckeditor/ckeditor5-vue/pull/209 from the `ckeditor5-vue` concerned another issue, strictly related to the Vue 3, which tries to convert the editor instance to a proxy.

This issue concerns the case, when the model value is changed, but the editor is not ready yet, so the watcher is not able to set the data on the editor instance. I will fix this issue soon.

**Comment by pomek** [comment]
Released as https://github.com/ckeditor/ckeditor5-vue2/releases/tag/v3.0.1.
