### ISSUE TITLE
SourceEditing plugin fails to build

### ISSUE THREAD

**Issue by lnwhitling** [ckeditor/ckeditor5-vue2#23]
I'm using the Classic Editor component locally, which works fine on its own in my vue-2 project.

I then wanted to add the Source Editing plugin for the tool bar. So I ran npm install --save @ckeditor/ckeditor5-source-editing, and pulled it locally into my component.

But now when trying to build, I get the following error:
 error  in ./node_modules/@ckeditor/ckeditor5-source-editing/theme/sourceediting.css
Syntax Error: ModuleNotFoundError: Module not found: Error: Can't resolve './@ckeditor/ckeditor5-theme-lark/theme/mixins/_focus.css' in 'C:\...\node_modules\@ckeditor\ckeditor5-source-editing\theme'

I've tried npm-installing the lark theme to my project, but still no joy.

package.json:
```
"@ckeditor/ckeditor5-build-classic": "^34.1.0",
"@ckeditor/ckeditor5-source-editing": "^34.1.0",
"@ckeditor/ckeditor5-vue2": "^3.0.1",
```

Vue Component:
```
<template>
    <div>
        <ckeditor :editor="editor" :config="editorConfig"></ckeditor>
    </div>
</template>

<script>
    import CKEditor from '@ckeditor/ckeditor5-vue2';
    import ClassicEditor from '@ckeditor/ckeditor5-build-classic';
    import SourceEditing from '@ckeditor/ckeditor5-source-editing';

    export default {
        data() {
            return {
                editor: ClassicEditor,
                editorConfig: {
                    plugins: [SourceEditing],
                    toolbar: ['sourceEditing']
                }
            }
        },
        components: {
            'ckeditor': CKEditor.component
        }
    }
</script>
```

**Comment by pomek** [comment]
Hi @lnwhitling, 

The `@ckeditor/ckeditor5-build-classic` package is one of [CKEditor 5 builds](https://ckeditor.com/docs/ckeditor5/latest/installation/advanced/alternative-setups/predefined-builds.html). You cannot extend a ready-to-use package with a custom plugin.

Read more about how to add a new plugin to build in the documentation - 
 https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/installing-plugins.html#adding-a-plugin-to-a-build.

In case of further questions, let us know.

**Comment by lnwhitling** [comment]
Ah of course - understood.

Thanks for that!
