### ISSUE TITLE
Programmatically focus/blur editor instance

### ISSUE THREAD

**Issue by urukai** [ckeditor/ckeditor5-vue2#32]
### Context
I am building some kind of Gutenberg-Editor, with multiple blocks for different kinds of content (headings, paragraph, images et al). Now, when the user writes a text inside a paragraph and hits the enter key, a new paragraph-block is instantly created and inserted after the current block being edited. 

The new paragraph-block contains its own editor. After insertion, the the new editor inside the new block should be focussed.

What I tried:

a) template:
```
<ckeditor :editor="editor" 
          v-model="myContent"
          :config="editorConfig"></ckeditor>
```

b) component data:

```
data() {
    myContent: '',
    editor: BalloonEditor,
    editorConfig: {
        // Toolbar and stuff...
    }
}
```

After the new paragraph block is created, I want to focus the editor inside the new block, after waiting for the editor to be ready:

```
this.$nextTick(() => {
    this.editor.editing.view.focus(); // <-- not working, "editing" is not defined
});

```

Everything else is working fine.

**How can I set focus on one instance by code?**

Thank you for your help!

**Comment by pomek** [comment]
Could you share more details regarding the integration with CKEditor? I am unsure whether I understood your problem, and I would need more information to provide an answer.

**Comment by urukai** [comment]
Basically, I am using vue components inside a laravel application. One component wraps multiple other vue components where each of it contains one instance of a `<ckeditor>`.

My plan is to generate another `<ckeditor>` whenever the user presses the enter key inside of one of these editors. So, instead of generating a p-element inside ckeditor, I would like to generate a whole new `<ckeditor>`-instance and set the cursor there.

I managed to generate an new instanace and place it after the current `<ckeditor>` when pressing the `enter` key, but the cursor is still blinking inside the «old» one. I am capturing the key strokes by adding a small extra plugin, such as:

```
export const enterToShiftEnter = ( editor ) => {
    editor.editing.view.document.on('enter', (evt, data) => {
        editor.execute( 'shiftEnter' );
        // custom event manager, to be notified when enter key was pressed
        EventManager.$emit( 'entercatched', data );
        data.preventDefault();
        evt.stop();
    });
}

```

So, when typing inside a `<ckeditor>`, I know which one is the current, and I know consequently which one is the next to be focussed on.

In the wrapping component, I can catch the `entercatched`-event emitted by the EventManager and place a new inner component with a `<ckeditor>`.

Later, these contents will be exported via REST-Api, and every `<ckeditor>` will generate a separate item to be consumed by an WebApp. The idea is to have separate items for paragraphs, titles and more.

**Comment by psmyrek** [comment]
The `shiftEnter` command that you manually call, operates on a selection, so this may not work properly with the code that tries to focus a newly created editor at the same time.

Please try to make the following changes:
1. Listen to the event emitted after the `shiftEnter` command has been executed and only then create a new editor.
   ```js
   export const enterToShiftEnter = ( editor ) => {
       const shiftEnterCommand = editor.commands.get( 'shiftEnter' );

       editor.editing.view.document.on( 'enter', ( evt, data ) => {
           shiftEnterCommand.once( 'afterExecute', () => {
               // custom event manager, to be notified when enter key was pressed
               EventManager.$emit( 'entercatched', data );
           });

           editor.execute( 'shiftEnter' );
        
           data.preventDefault();
           evt.stop();
       });
   }
   ```

2. In the `<ckeditor>` component you're creating, you don't immediately have access to an instance of that editor, because it needs some time to be fully initialized and created. Try listening to the `ready` event.

   ```
   <ckeditor :editor="editor" 
             v-model="myContent"
             :config="editorConfig"
             @ready="onEditorReady"></ckeditor>
   ```

   ```js
   methods: {
       onEditorReady( editor ) {
           editor.editing.view.focus();
       }
   }
   ```

**Comment by urukai** [comment]
I got a type error:

`Uncaught TypeError: Cannot read properties of undefined (reading 'once')`

But I've managed to get it working with a (slightly renamed) plugin:

```
export const enterToNewParagraphBlock = ( editor ) => {
    editor.editing.view.document.on('keydown', (evt, data) => {
        if ( data.keyCode === 13 && ! data.shiftKey ) {
            EventManager.$emit( 'newparagraph', data );
            data.preventDefault();
            evt.stop();
        }
    });
}
```

And your second point with the `onEditorReady`-method did the trick.

**Your help is very much appreciated! Thanks a lot!**
