### ISSUE TITLE
nothing in menu all in show more

### ISSUE THREAD

**Issue by nbilly7** [ckeditor/ckeditor5-vue2#9]
**I work with** 
"@ckeditor/ckeditor5-build-classic": "^24.0.0",
"@ckeditor/ckeditor5-vue2": "^1.0.5",
"vue": "^2.6.10"
and
"vuetify": "^2.3.16"

**This is my utilisation of ckeditor:**

```
<template>  
[...]  
<ckeditor :editor="editor" v-model="editorData" :config="editorConfig"></ckeditor>  
[...]  
</template>  
<script>  
import CKEditor from '@ckeditor/ckeditor5-vue2';  
import ClassicEditor from '@ckeditor/ckeditor5-build-classic';  
import '@ckeditor/ckeditor5-build-classic/build/translations/fr';  
export default {   
  components: {  
    ckeditor: CKEditor.component  
  },  
  data () {  
    return {  
      editor: ClassicEditor,  
      editorData: 'bla bla bla <br> bla bla bla',  
      editorConfig: {  
        language: 'fr',  
        toolbar: ['heading', '|',  
          'bold', 'italic', 'bulletedList', 'numberedList', 'blockQuote', '|',  
          'undo', 'redo']  
      }  
    };  
  }  
</script>  
```
**This is my first display where all items are in the show more button:** 
![Capture du 2020-12-21 12-57-29](https://user-images.githubusercontent.com/76433230/102774878-1b73fa00-438c-11eb-8692-68ddf4880e81.png)

**and this is the display when I change a heading which is the result I want:**
![Capture du 2020-12-21 12-58-01](https://user-images.githubusercontent.com/76433230/102774909-2dee3380-438c-11eb-82bc-f83508379267.png)

**Question:** Why items are in the show more button whereas there is space to display all items.

**Comment by LukaszGudel** [comment]
Hi @nbilly7, I tried to test your use case to get a similar toolbars but I could not recreate this issue.  I've tested this with clean vue project as well as in a project with vuetify where I use some library components, classes and fixed widths. In both cases toolbar is displaying properly. Could you share your project with us? Your issue could be caused by some specific mix of vuetify components and styles and having source code will be the best way to debug this.

**Comment by nbilly7** [comment]
Sorry I can't share my project... I have a solution that is to use CKEditor 4. 
If you cannot recreate this issue you can close it.
Thank you for your time.

**Comment by d4rkr3pt0r** [comment]
@nbilly7 I know you found a solution but this is what I think that causing your issue (may be helpful for others). Probably, your page or modal has a CSS transform while showing which makes the page to be created from a very small size. So the editor adapts its toolbar with that page's width and puts all toolbar buttons in a more-button.

**Comment by redcomethk** [comment]
> @nbilly7 I know you found a solution (actually not a solution but removing what makes the issue!) but this is what I think that causing your issue (may be helpful for others). Probably, your page or modal has a CSS transform while showing which makes the page to be created from a very small size. So the editor adapts its toolbar with that page's width and puts all toolbar buttons in a more-button.

I am actually having the same problem and it seems to be the case. I'm using the editor in a dialog. Do you have any solution for this problem?

**Comment by d4rkr3pt0r** [comment]
@nbilly7 Remove `CSS Transform` properties from that dialog. That would fix the problem.

**Comment by AndrewBeznosko** [comment]
To fix it just add to the config:
```
config: {
  toolbar: {
    shouldNotGroupWhenFull: true,
  }
}
```

**Comment by ikhidebright** [comment]
currently having the same issue `shouldNotGroupWhenFull: true` and setting transform to none doesn't fix it
